### ISSUE TITLE
One of my lectures hasn't been counted

### ISSUE THREAD

**Issue by peclarke** [kentonlam/how-behind#1]
Here's my timetable: https://timetable.my.uq.edu.au/even/rest/calendar/ical/ad355285-56c6-4d0d-bdc8-bc5e01c008d5

I had a MATH1051 Lecture from 3-4 today (6th April). It's currently 5 pm and nothing has been updated on the screen. I've had the tab open on Chrome most of the day and I've found it extremely useful so far. 

Edit: It seems it marked my lecture as already caught up when I did not click on any buttons. 

![Screen Shot 2020-04-06 at 5 11 43 pm](https://user-images.githubusercontent.com/30831649/78531921-b9895980-7829-11ea-9428-83558812390b.png)

**Comment by katrinafyi** [comment]
I believe that happens if the tab is open when the class ends. It should become "behind" after you refresh, definitely not already caught up. Did you have the website open on any other devices?

I'll try and fix it when I have time.

**Comment by peclarke** [comment]
I was refreshing periodically during the day and the other classes were working. There's a possibility I accidentally clicked it but I don't recall ever seeing it on there. I only had it up on my Mac.

**Comment by peclarke** [comment]
Yep, it's happened again. Had a MATH1051 lecture from 1-2 pm today (same one as before) which has not been counted as missed nor has it been counted in the caught up section. This screenshot was taken at 2:51 pm, 51 minutes after the lecture had finished. Same as before, had the tab open for the duration of the day with constant refreshes. 

![Screen Shot 2020-04-07 at 2 49 40 pm](https://user-images.githubusercontent.com/30831649/78631268-3fb3a780-78df-11ea-9893-9af5031f2b6a.png)

**Comment by katrinafyi** [comment]
I believe I've found the issue. If you refreshed during a class, it would miss that class. Should be fixed now. 

It now updates automatically with the tab open (check browser console F12 to see next update time). I've also optimised various things for noticeable speed-ups, particularly when changing pages.

Let me know if it's fixed for you.

**Comment by katrinafyi** [comment]
Hi, can you confirm if this bug has been fixed or still happens? 

I've pushed a number of changes in the past two weeks and I'm fairly certain it's been patched.

**Comment by peclarke** [comment]
Yep, haven't experienced the issue since!

**Comment by katrinafyi** [comment]
After investigating, How Behind is accurate according to the given iCal URL. UQ's Allocate+ iCal feed is broken. 😄
